/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

const MAX = 4000000

const calculateFib = (twoBack = 1, oneBack = 2, current = 0) => {

    if ((oneBack <= MAX) && !(oneBack % 2)) current += oneBack

    return twoBack + oneBack <= MAX
      ? calculateFib(oneBack, twoBack + oneBack, current)
      : current
}

const result = calculateFib()
console.log(result)
